# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # TODO: Set link to an EOX box when avaiable.
  #config.vm.box_url = "http://downloads.eox.at/boxes/centos-6.7-x86_64.box"

  config.vm.hostname = "aeolus-server-devel"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8400
  config.vm.network :forwarded_port, guest: 8000, host: 8401

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  config.vm.synced_folder "../../eoxserver", "/usr/local/eoxserver", owner: "root", group: "root"
  config.vm.synced_folder "../../eoxs-allauth", "/usr/local/eoxs-allauth", owner: "root", group: "root"
  config.vm.synced_folder "../../Aeolus-Server", "/usr/local/aeolus", owner: "root", group: "root"
  #config.vm.synced_folder "../../vires-aeolus_ops", "/usr/local/vires-aeolus_ops", owner: "root", group: "root"
  config.vm.synced_folder "../", "/home/vagrant/Aeolus", owner: "vagrant", group: "vagrant"
  # data directory (Change to your custom data directory if necessary.)
  config.vm.synced_folder "../data", "/mnt/data", owner: "root", group: "root"

  # Shell provisioning
  config.vm.provision :shell, :inline => "cd /home/vagrant/Aeolus/scripts/ ; /bin/sh ./install.sh -d"
  config.vm.provision :shell, :inline => "sudo systemctl restart eoxs_wps_async.service" , run: "always"
  config.vm.provision :shell, :inline => "sudo systemctl restart httpd.service" , run: "always"

  # Adjust Virtualbox configuration
  config.vm.provider "virtualbox" do |v|

    # Custom name
    v.name = "aeolus-server-devel"

    # Increase memory and cpus
    v.customize ["modifyvm", :id, "--memory", 1024, "--cpus", 2]
    # Increase performance i.e. don't use swap extensively 
    v.customize ["modifyvm", :id, "--ioapic", "on", "--largepages", "off", "--vtxvpid", "off"]

    # Use GUI for debugging purposes
    #v.gui = true
  end
end
